### ISSUE TITLE
Is there a wrong img?

### ISSUE THREAD

**Issue by MoeShan** [aspnet/Docs.zh-cn#53]
https://docs.microsoft.com/zh-cn/aspnet/mvc/overview/getting-started/introduction/adding-a-controller

image 8  should be like newimage8

![image8](https://user-images.githubusercontent.com/8566898/41335844-d017bfec-6f1c-11e8-9ffe-55a029da055c.png)
![newimage8](https://user-images.githubusercontent.com/8566898/41335845-d047ef14-6f1c-11e8-9ccb-c041af0df31c.png)

**Comment by CeciAc** [comment]
Hello, @MoeShan

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
